# Generated by Django 5.2 on 2025-04-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gardenBookApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livre",
            name="stock",
        ),
        migrations.AddField(
            model_name="livre",
            name="dispo",
            field=models.BooleanField(default=True),
        ),
    ]
