# Generated by Django 5.2 on 2025-04-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gardenBookApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livre",
            name="id",
        ),
        migrations.AlterField(
            model_name="livre",
            name="ISBN",
            field=models.CharField(
                max_length=13, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
