# Generated by Django 5.2 on 2025-04-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gardenBookApp", "0002_remove_livre_id_alter_livre_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="livre",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="livre",
            name="ISBN",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
